### ISSUE TITLE
Research | Microstructure: Merge to single page

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/neuro.polymtl.ca#35]
here: https://neuro.polymtl.ca/research/mapping-tissue-microstructure/README.html

it is broken down across multiple pages-- i suggest we merge in one page

**Comment by kousu** [comment]
![Screenshot 2021-11-19 at 14-01-06 Mapping Tissue Microstructure — NeuroPoly Lab](https://user-images.githubusercontent.com/987487/142677038-328f5fc1-9842-4245-b9c9-f35a6f4ce415.png)

better? :)
