### ISSUE TITLE
Add Dr. De Leener's students

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/neuro.polymtl.ca#41]
@benjamindeleener I only have their name:

Andjela Dimitrijevic
Colline Blanc
Daniel Ridani
Noee Ducros-Chabot
Louis-Joseph Laberge
Erjun Zhang
Anes Belfodil
Antoine El-Hachem

Could you please let me their status (MSc, PhD, intern, PostDoc, RA) ? Thank you

**Comment by jcohenadad** [comment]
Ideally each student should be responsible to add themselves
