### ISSUE TITLE
TOC scrolls with the page

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/neuro.polymtl.ca#44]
Here's what's happening to the TOC when we scroll the page: it disappears:

https://user-images.githubusercontent.com/2482071/144539079-d8715d48-436e-4a4f-b7b0-a44c7a0d9910.mov

However, with the [native theme template](https://executablebooks.org/en/latest/), it doesn't happen:

https://user-images.githubusercontent.com/2482071/144539124-baec396d-0dc9-47c5-8906-09d5927256cf.mov

So it might be possible to fix this while keeping the same theme?

**Comment by kousu** [comment]
Mayyyybe. Notice that their ToC is a lot shorter than ours. Maybe that has something to do with why it's working for them?

All my customizations are in

https://github.com/neuropoly/neuro.polymtl.ca/blob/f4dbbe42cc7e5900139d57d275571a00f94670f9/_static/theme.css#L2-L158

nothing in there should have had this effect, but I suppose anything is possible.

**Comment by jcohenadad** [comment]
Started a debugging branch: https://github.com/neuropoly/neuro.polymtl.ca/tree/jca/toc-sliding

**Comment by jcohenadad** [comment]
> Notice that their ToC is a lot shorter than ours. Maybe that has something to do with why it's working for them?

I tried shortening the TOC entry, but it doesn't help:

https://user-images.githubusercontent.com/2482071/144715993-a64a11fd-4c90-4985-828d-06bdf73d8ead.mov

**Comment by jcohenadad** [comment]
Even without using the custom `_static/theme.css`, the issue persists. So it is likely not related to the theme.css file 🤷

**Comment by jcohenadad** [comment]
victory 🎉 

https://user-images.githubusercontent.com/2482071/144716356-6cfbaf12-2260-4dbb-a21e-31be3bbec576.mov

The solution was to add this line in the conf.py file:
https://github.com/neuropoly/neuro.polymtl.ca/blob/ffcafd6a748ddefac05b81a8c590f4db49b8cc7c/conf.py#L66

I got inspired by the original [conf.py](https://github.com/executablebooks/meta/blob/master/docs/conf.py) file
