### ISSUE TITLE
Add job position for data curator

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/neuro.polymtl.ca#55]
in addition to the soft dev announce above, i'd also like to consider data manager/data curator for BIDS databases (and our upcoming public database sharing with Praxis, UNF, Ste Justine, DonUM, etc.).  Please throw your ideas/suggestions here

**Comment by kousu** [comment]
Off the top of my head:


## Responsibilities

* Collect raw data via email, DropBox, Google Drive, ssh, http, smb, and via our local LAN (?) and reformat it to be [BIDS](https://bids-specification.readthedocs.io/)-compliant
* Anonymize data ([defacing](https://open-brain-consent.readthedocs.io/en/stable/anon_tools.html#faces-dental-stripping), removal of identifying metadata)
* Review data submitted by students and researchers.
  * Verify:
    * Image quality
    * Taxonomy (i.e. file names)
    * Metadata (in `.tsv` and `.json` files)
    * Anonymization
  * Merge pull requests
* Identify validation steps that could be automated and work with the dev team to implement them
* Comply with IRB, consent and copyright compliance terms
  * Verify and perform data removal when requested by subjects
* Administer dataset access control; in compliance with license/ethics terms
* Monitor weekly(?) dataset backups
* Schedule and run data disaster recovery drills
* Participate in [BIDS](https://github.com/bids-standard/bids-specification) to extend its use-cases

## Skills:

* some familiarity with the unix command line (`ls`, `find`, `diff`, `du`, `xargs`, `curl`, `sha256sum`/`md5sum`)
* experience with experimental ethics clearances
* `git`
* familiarity with [dicom](https://en.wikipedia.org/wiki/DICOM) and [nifti](https://nifti.nimh.nih.gov/nifti-2) formats
* familiarity with neuromorphology

## Bonus Skills

* python scripting
  * e.g. can you open 1013 images and find their average voxel count?
  * can you write validation scripts?
* [`jq`](https://stedolan.github.io/jq/)
* The use of `git rebase`, `git commit --amend`, `git push --force` and their implications
* `git filter-repo`, and its implications
  * Necessary to comply with data removal requests

**Comment by jcohenadad** [comment]
thank you @kousu ! i'll start a PR today

**Comment by jcohenadad** [comment]
Here: https://neuro.polymtl.ca/job-opportunities/data-curator.html
