### ISSUE TITLE
Some images are missing

### ISSUE THREAD

**Issue by gaspardcereza** [neuropoly/neuro.polymtl.ca#66]
Some images are not visible on the website. For example on [this page](https://neuro.polymtl.ca/research/rf-and-shim-coil-design.html): 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/54723104/161773928-928f3eda-fff2-4bb5-a49f-dd672580684e.png">

**Comment by jcohenadad** [comment]
Thank you @gaspardcereza 

Fixed in https://github.com/neuropoly/neuro.polymtl.ca/commit/ab212641b6f91f577c744f58941d3a07942fe6cc
