### ISSUE TITLE
Builds failing

### ISSUE THREAD

**Issue by mguaypaq** [neuropoly/neuro.polymtl.ca#78]
The website builds are currently failing: [link](https://github.com/neuropoly/neuro.polymtl.ca/actions/runs/4427265183/jobs/7764609251#step:5:70).

This is probably the same problem as last week for the internal website ([intranet#95](https://github.com/neuropoly/intranet.neuro.polymtl.ca/issues/95)), due to a new release of one of the dependencies.

**Comment by jcohenadad** [comment]
FWIW I tried https://github.com/neuropoly/neuro.polymtl.ca/issues/78#issuecomment-1470424195 locally and it fixed the issue

**Comment by mguaypaq** [comment]
I finished the upgrade in:
https://github.com/neuropoly/neuro.polymtl.ca/commit/d0d5064ff22172774993549b176e12a2c845ec32

The new version is up, and the build is succeeding:
https://github.com/neuropoly/neuro.polymtl.ca/actions/runs/4672198266
