### ISSUE TITLE
publi filtering should be AND instead of OR

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/neuro.polymtl.ca#88]
see slack https://neuropoly.slack.com/archives/C023QTPARSL/p1681248148092819?thread_ts=1680544620.591689&cid=C023QTPARSL

**Comment by mguaypaq** [comment]
Fixed in https://github.com/neuropoly/neuro.polymtl.ca/commit/35984cc8023922367245302a0182692ebaac52a2.
